env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: detect
rules:
  react/jsx-filename-extension:
    - off
  import/prefer-default-export:
    - off
  import/no-unresolved:
    - off
  import/extensions:
    - off
  react/jsx-props-no-spreading:
    - off
  react/button-has-type:
    - off
  overrides:
    - files: src/Pages/404/*
      rules:
        no-param-reassign: 0 
